---
methods:
  closedcaptions.enabled:
    response: |
      function f(ctx, params) {
        const ccs = ctx.get('closedCaptionsSettings');
        if ( params && params.hasOwnProperty('value') ) {
          // Setter called:
          // Cause an accessibility.onClosedCaptionsSettingsChanged event
          // (done via post-method trigger on closedcaptions.enabled method)
          // Save for when accessibility.closedCaptionsSettings is called
          ccs.enabled = params.value;
          ctx.set('closedCaptionsSettings', ccs);
          return true;
        } else {
          // Getter called:
          // Return what we last saved when this func was called as a setter
          return ccs.enabled;
        }
      }
  accessibility.closedCaptionsSettings:
    response: |
      function f(ctx, params) {
        // Getter called... Return our stashed value, per last setter call
        const ccs = ctx.get('closedCaptionsSettings');
        return ccs;
      }
